service: serverless-amazon-alexa

provider:
  region: eu-west-1
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 5
  environment:
    CONFIG: ${file(./config/${self:provider.stage}/config.json.config)}
    STAGE: ${self:provider.stage}

functions:
  speech:
    handler: src/index.speech
    events:
      - alexaSkill

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules: true
